# .github/workflows/publish-allure-report.yml
name: Publish Allure Report

on:
  workflow_run:
    workflows: ["Unit Tests"]
    types: [completed]

jobs:
  allure-report:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          name: allure-results-unit
          path: allure-results

      - name: Install Allure CLI
        run: |
          sudo apt update
          sudo apt install -y allure

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
