# .github/workflows/unit-tests.yml
name: Unit Tests

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    env:
      ASPNETCORE_ENVIRONMENT: QA

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Debug

      - name: List output directory before tests
        run: ls -R ./tests/UnitTests/bin/Debug/net9.0

      - name: Run Unit Tests
        run: dotnet test ./tests/UnitTests/UnitTests.csproj --no-build --configuration Debug --logger "console;verbosity=detailed"
