# .github/workflows/unit-tests.yml
name: Unit Tests

on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]

jobs:
  unit-tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    env:
      TEST_ENVIRONMENT: QA

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Debug

      - name: Run Unit Tests
        run: dotnet test ./tests/UnitTests/UnitTests.csproj --no-build --configuration Debug
        # generate allure-results here

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-unit
          path: tests/UnitTests/bin/Debug/net9.0/allure-results
